/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./assets/**/*.{html,js,hbs}",
    "./*.html",
    "./main.js",
    "./docs/**/*.html"
  ],
  theme: {
    extend: {
      colors: {
        'brand-blue': '#008DD2',    // Синий цвет из брендбука
        'brand-gray': '#4D4D4D',    // Темно-серый цвет из брендбука
        'brand-light': '#F4F6F9',   // Светло-серый цвет из брендбука
        'brand-white': '#FFFFFF',   // Белый цвет из брендбука
        
      },
      fontFamily: {
        'calibri': ['Calibri', 'sans-serif'],
      },
      fontSize: {
        // Настройки размеров шрифтов из брендбука
        h1: '68px',
        h2: '48px',
        h3: '32px',
        h4: '26px',
        h5: '20px',
        h6: '18px',
        body: '24px',
        'body-secondary': '20px',
        'caps-bold': '20px',
        'buttons': '20px',
        'caps-regular': '18px',
        'caption-regular': '24px',
        'caption-light': '18px',
        'caption-form': '16px',
        'caption-form-light': '14px',
      },
      fontWeight: {
        light: 300,
        regular: 400,
        bold: 700,
      },
      lineHeight: {
        '1': '1',
        'auto': 'auto',
        '1em': '1em',
        '1.2': '1.2',
        '1.5': '1.5',
      },
      objectPosition: {
        'bottom': 'bottom',
        'center': 'center',
        'top': 'top',
        'left': 'left',
        'right': 'right',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
      },
      spacing: {
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '13': '3.25rem',
        '14': '3.5rem',
        '15': '3.75rem',
        '16': '4rem',
        '17': '4.25rem',
        '18': '4.5rem',
        '19': '4.75rem',
        '20': '5rem',
        '21': '5.25rem',
        '22': '5.5rem',
        '23': '5.75rem',
        '24': '6rem',
        '25': '6.25rem',
        '26': '6.5rem',
        '27': '6.75rem',
        '28': '7rem',
        '29': '7.25rem',
        '30': '7.5rem',
        '31': '7.75rem',
        '32': '8rem',
        '33': '8.25rem',
        '34': '8.5rem',
        '35': '8.75rem',
        '36': '9rem',
        '37': '9.25rem',
        '38': '9.5rem',
        '39': '9.75rem',
        '40': '10rem',
      },
    },
    // Настройка брейкпоинтов для mobile-first подхода
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1921px',
    },
  },
  plugins: [],
}